sudo: required
services:
  - docker

before_install:
  - docker build -t dhikshith/weather-application -f Dockerfile.dev .

script:
  - docker run dhikshith/weather-application npm run test -- --coverage
