version: "3"
services:
  react-app:
    stdin_open: true
    #always,"no",onfailure,unless-stopped
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
